module.exports = {
  ARABIC_NUMERALS: 10,
  HEXADECIMAL_NUMERALS: 16,
  CASE_INSENSITIVE_LATIN_ALPHABET: 26,
  CASE_INSENSITIVE_ALPHANUMERIC: 36,
  CASE_SENSITIVE_LATIN_ALPHABET: 52,
  CASE_SENSITIVE_ALPHANUMERIC: 62,
  ASCII_EXCLUDING_SPACE: 94,
  ASCII_PRINTABLE_CHARACTERS: 95,
  EXTENDED_ASCII_PRINTABLE_CHARACTERS: 218
}
